---
# tasks file for systemd-hybris
- name: copy_hybris
  become: yes
  template:
    src: "hybris_service.j2"
    dest: "/etc/systemd/system/hybris.service"
    owner: root
    group: hybris
    mode: 0775

- name: reload_service
  become: yes
  shell: systemctl daemon-reload

- name: enable_service
  become: yes
  service:
    name: hybris
    enabled: yes
