---
- name: Install hybris
  become: true
  hosts: backoffice
  
  roles:

   - hybris_configuration
   - williamyeh.oracle-java
   - java_configuration
   - jeffhung.mysql
   - configure_nfs
   - hybris_deploy
   - systemd-hybris



